# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_p.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(614, 550)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.doubleSpinBox_s_m = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_s_m.setObjectName("doubleSpinBox_s_m")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_s_m)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.doubleSpinBox_s_n = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_s_n.setObjectName("doubleSpinBox_s_n")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_s_n)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.doubleSpinBox_s_k = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_s_k.setObjectName("doubleSpinBox_s_k")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_s_k)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.doubleSpinBox_z_p = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_z_p.setObjectName("doubleSpinBox_z_p")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_z_p)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.doubleSpinBox_z_q = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_z_q.setObjectName("doubleSpinBox_z_q")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_z_q)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.doubleSpinBox_z_r = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_z_r.setObjectName("doubleSpinBox_z_r")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_z_r)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.doubleSpinBox_rho_a = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_rho_a.setObjectName("doubleSpinBox_rho_a")
        self.horizontalLayout.addWidget(self.doubleSpinBox_rho_a)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.doubleSpinBox_rho_b = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_rho_b.setObjectName("doubleSpinBox_rho_b")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_rho_b)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\"> S(t) = mt + nsin(kt)</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "Enter m:"))
        self.label_8.setText(_translate("Dialog", "Enter n:"))
        self.label_9.setText(_translate("Dialog", "Enter k:"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">z(t) = pt + qcos(rt)</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "Enter p:"))
        self.label_10.setText(_translate("Dialog", "Enter q:"))
        self.label_11.setText(_translate("Dialog", "Enter r:"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">&rho; (&omega;) = a (&omega;) (b - &omega;)</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Enter a:"))
        self.label_6.setText(_translate("Dialog", "Enter b:"))

